Fix ClassCastException in OntrackMultiChoiceParameter
jenkinsci/ontrack-plugin pull request #43
Opened 2018-02-10 10:34 UTC by DavidCADanneels

If the OntrackMultiChoiceParameter displays only one option, we get a ClassCastException, because this option is passed as a single Boolean, while we expected a JSONArray of Booleans.

With this fix we first verify the object type and handle it differently in case of a Boolean.
This has been tested ok locally.

2018-02-13 12:54 UTC, dcoraboeuf requested changes

2018-02-13 12:54 UTC, dcoraboeuf commented on src/main/java/net/nemerosa/ontrack/jenkins/OntrackMultiChoiceParameterDefinition.java
> +                if ((Boolean) jsonArray.get(i)) {
Make the code more secure by using something like:

```
if (i < jsonArray.size() && jsonArray.get(i) instanceof Boolean && (Boolean) jsonArray.get(i)
```

(better store the indexed variable somewhere)

2018-02-13 14:10 UTC, DavidCADanneels commented
The if clause has been updated and tested locally

2018-02-13 14:11 UTC, dcoraboeuf approved these changes

2018-02-13 14:11 UTC, merged

2018-02-15 10:23 UTC, dcoraboeuf commented
Fixed in 2.30.3.8